### ISSUE TITLE
Make changes in function sage_boolexp

### ISSUE THREAD

**Issue by hrithik254** [hrithik254/DigitalLogicsOnSage#1]
`def sage_boolexp(string):

    ""this function converts boolean expresssion written 
        using *, +, ' representing AND, OR, NOT 
        operations to sage interpretable expression""
    
    
    literal_list0 = ["&" if i == "*" else i for i in string]
    literal_list1 = ["|" if i == "+" else i for i in literal_list0]
    for i in range(len(literal_list1)):
        if literal_list1[i] == "'":
            del literal_list1[i]
            if literal_list1[i-1] == ")":
                j = i-1
                while literal_list1[j] != "(":
                    j += -1
                literal_list1.insert(j,'~')
                i += 1
            else:
                literal_list1.insert(i-1,"~")
    return_string = ''
    for literal in literal_list1:
        return_string += literal
    return return_string`
This is the current code which converts a boolean expression entered by the user using * for AND, + for OR and ' for NOT.
currently it requires the user to enter * to indicate AND, what I want is that the user enters `ab' + bc` instead of `a*b' + b*c`
The main purpose of this function is to save time. note: the * and + expressions can contain spaces but `y'` cannot be written as `y '`. `a + b *d'`is acceptable but `a + b *d '` would give error. This is alo a potential issue, but it can be fixed later

**Comment by AmaaniGoose** [comment]
On it

**Comment by AmaaniGoose** [comment]
Issue resolved
